version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: oneconnector
    ports:
      - 5435:5432
  rabbitmq:
    image: bitnami/rabbitmq
    environment:
      RABBITMQ_USERNAME: testing
      RABBITMQ_PASSWORD: testing
      RABBITMQ_VHOST: oneconnector
    ports:
      - 5679:5672
  dbadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: testing@testing.com
      PGADMIN_DEFAULT_PASSWORD: testing
    ports:
      - 8080:80
    links:
      - db:db
  fluentd:
    image: fluent/fluentd
    entrypoint: ["fluentd", "-c", "/etc/fluent/fluent.conf", "-vv"]
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - "./fluentd/fluent.conf:/etc/fluent/fluent.conf"